export const PLANNING_TASKS_PUBLICATION = 'planning.tasks'
export const PLANNING_TASK_NOTE_METHOD = 'planning.task.note'
export const PLANNING_TASK_TICK_OFF_METHOD = 'planning.task.tickOff'
export const PLANNING_TASK_RESUME_METHOD = 'planning.task.resume'
export const PLANNING_TASK_EDIT_METHOD = 'planning.task.edit'
export const PLANNING_TASK_DISCARD_METHOD = 'planning.task.discard'
export const PLANNING_TASK_ARCHIVE_METHOD = 'planning.task.archive'
