import './archiveTaskMethod'
import './discardAllArchivedTasksMethod'
import './discardTaskMethod'
import './editTaskMethod'
import './noteTaskMethod'
import './resumeTaskMethod'
import './tickOffTaskMethod'
