import '../../../../../../imports/planning/task/api/methods'
import './archiveTaskMethod.test'
import './discardAllArchivedTasksMethod.test'
import './discardTaskMethod.test'
import './editTaskMethod.test'
import './noteTaskMethod.test'
import './resumeTaskMethod.test'
import './tickOffTaskMethod.test'
