name: CI

on:
  push:

  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v1

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install all dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test:unit
